language: cpp

os:
  - linux
  - osx

#compiler:
#  - gcc
#  - clang

#branches:
#  only:
#    - master

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install build-essential cmake gettext git-core gpsd gpsd-clients libgps-dev wx-common libwxgtk3.0-dev libglu1-mesa-dev libgtk2.0-dev wx3.0-headers libbz2-dev libtinyxml-dev libportaudio2 portaudio19-dev libcurl4-openssl-dev libexpat1-dev libcairo2-dev libarchive-dev liblzma-dev libexif-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cairo libexif libarchive cmake gettext wxmac; fi
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "gzuRKPoISDCbjfRdI+KS0H3/9T4CDLybTxLwirUJ660IaFTewNYXj/pyOJOr7miOrBmQaJQw7aKAG4fpfbHpY0kkLQe2JHaJv84uyuev4QuJGtfyim3a2U4FbxtCyyjREyGI15enBra3N1xKtQqNbnkgOCKPtWSAlX4rf1elj5A="

addons:
  coverity_scan:
    project:
      name: "nohal/iacfleet_pi"
      description: "Build submitted via Travis CI"
    notification_email: pavel@kalian.cz
    build_command_prepend: "mkdir -p build; cd build; cmake ..; make clean"
    build_command:   "make"
    branch_pattern: coverity_scan
#    build_script_url: "https://raw.githubusercontent.com/nohal/iacfleet_pi/master/scan_script.sh"
