version: 0.9.{build}

clone_folder: c:\projects\iacfleet_pi
shallow_clone: true
image:
- Visual Studio 2015

platform:
  - Win32

configuration: Release
test: OFF

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86'

  # sent environment variables for wxWidgets
  - set WXPARENT=C:\
  - set WXWIN=C:\wxWidgets-3.0.2
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
  - cmd: SET PATH=%PATH%;%WXWIN%;%wxWidgets_LIB_DIR%;C:\Program Files (x86)\Poedit\Gettexttools\bin;

  # install dependencies:
  - choco install poedit nsis -x86

  # Download and unzip wxwidgets
#  - ps: Start-FileDownload http://downloads.sourceforge.net/project/wxwindows/3.0.2/wxWidgets-3.0.2.zip
  - ps: Start-FileDownload http://downloads.sourceforge.net/project/opencpnplugins/opencpn_packaging_data/wxWidgets-3.0.2.7z
  - cmd: 7z x wxwidgets-3.0.2.7z -o%WXPARENT% > null

  # some debugging information
  - set
  # - cmake --help

  # build wxWidgets
#  - cmd: cd %WXWIN%\build\msw\
#  - cmd: nmake -f makefile.vc BUILD=release SHARED=1 CFLAGS=/D_USING_V120_SDK71_ CXXFLAGS=/D_USING_V120_SDK71_
#  - cmd: nmake -f makefile.vc BUILD=debug SHARED=1 CFLAGS=/D_USING_V120_SDK71_ CXXFLAGS=/D_USING_V120_SDK71_

before_build:
  - cd c:\projects\iacfleet_pi
  - mkdir build
  - cd build
  - ps: Start-FileDownload http://downloads.sourceforge.net/project/opencpnplugins/opencpn_packaging_data/OpenCPN_buildwin.7z
  - cmd: 7z x -y OpenCPN_buildwin.7z -oc:\projects\iacfleet_pi
  - ps: Start-FileDownload http://downloads.sourceforge.net/project/opencpnplugins/opencpn_lib/4.2-vc120_xp/opencpn.lib
  - cmake -T v120_xp ..

build_script:
  - cmake --build . --config Release --target package

artifacts:
  - path: build\iacfleet_pi*.exe
    name: installer

