version: 2.0
jobs:
  build:
    docker:
      - image: nohal/opencpn-builder
    builder environment:
      OCPN_CI_BUILD: yes
    branches:
      only:
        - master
    steps:
      - run: pwd
      - run: ls -la
      - run: env
      - run: git clone "https://github.com/nohal/iacfleet_pi.git" work
      - run: mkdir work/build
      - run: cd work/build
      - run: cmake ..
      - run: make
